language: r

r:
  - release
  - devel

addons:
  apt:
    packages:
      - python3-dev
      - python3-pip

before_install:
  - >
    # python3 --version
    # travis_wait pip3 install --user --upgrade -q setuptools tensorflow tensorflow-hub tensorflow-datasets scipy requests pyyaml Pillow h5py pandas pydot
    # rm -f travis_wait*

sudo: false
cache:
 - pip
 - packages
warnings_are_errors: true
